name: Maven Deploy
on:
  push:
    branches:
      - dev
      - release
      - feat_workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java Environment
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
        server-id: maven
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        settings-path: ${{ github.action_path }}
    - name: Publish Maven
      run: mvn deploy -Dmaven.test.skip=true -s $GITHUB_ACTION_PATH/settings.xml
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USER_NAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
